/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as TimelineOverlayRouteImport } from './routes/timeline-overlay'
import { Route as SoundsRouteImport } from './routes/sounds'
import { Route as ScenesRouteImport } from './routes/scenes'
import { Route as RecordingsRouteImport } from './routes/recordings'
import { Route as IndexRouteImport } from './routes/index'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineOverlayRoute = TimelineOverlayRouteImport.update({
  id: '/timeline-overlay',
  path: '/timeline-overlay',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundsRoute = SoundsRouteImport.update({
  id: '/sounds',
  path: '/sounds',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenesRoute = ScenesRouteImport.update({
  id: '/scenes',
  path: '/scenes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRoute = RecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recordings': typeof RecordingsRoute
  '/scenes': typeof ScenesRoute
  '/sounds': typeof SoundsRoute
  '/timeline-overlay': typeof TimelineOverlayRoute
  '/videos': typeof VideosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recordings': typeof RecordingsRoute
  '/scenes': typeof ScenesRoute
  '/sounds': typeof SoundsRoute
  '/timeline-overlay': typeof TimelineOverlayRoute
  '/videos': typeof VideosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recordings': typeof RecordingsRoute
  '/scenes': typeof ScenesRoute
  '/sounds': typeof SoundsRoute
  '/timeline-overlay': typeof TimelineOverlayRoute
  '/videos': typeof VideosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/recordings'
    | '/scenes'
    | '/sounds'
    | '/timeline-overlay'
    | '/videos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/recordings'
    | '/scenes'
    | '/sounds'
    | '/timeline-overlay'
    | '/videos'
  id:
    | '__root__'
    | '/'
    | '/recordings'
    | '/scenes'
    | '/sounds'
    | '/timeline-overlay'
    | '/videos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecordingsRoute: typeof RecordingsRoute
  ScenesRoute: typeof ScenesRoute
  SoundsRoute: typeof SoundsRoute
  TimelineOverlayRoute: typeof TimelineOverlayRoute
  VideosRoute: typeof VideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline-overlay': {
      id: '/timeline-overlay'
      path: '/timeline-overlay'
      fullPath: '/timeline-overlay'
      preLoaderRoute: typeof TimelineOverlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sounds': {
      id: '/sounds'
      path: '/sounds'
      fullPath: '/sounds'
      preLoaderRoute: typeof SoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenes': {
      id: '/scenes'
      path: '/scenes'
      fullPath: '/scenes'
      preLoaderRoute: typeof ScenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings': {
      id: '/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof RecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecordingsRoute: RecordingsRoute,
  ScenesRoute: ScenesRoute,
  SoundsRoute: SoundsRoute,
  TimelineOverlayRoute: TimelineOverlayRoute,
  VideosRoute: VideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
