# Talkie App Definition
# Defines views and clickable targets for the Talkie app

app:
  type: native
  name: Talkie
  # Use the development build from TalkieSuite DerivedData
  path: /Users/arach/Library/Developer/Xcode/DerivedData/TalkieSuite-guavpoyqmfbntrgcygyesivttxyh/Build/Products/Debug/Talkie.app
  window:
    width: 1200
    height: 800
    center: true  # Center window to ensure HUD is visible

views:
  # Sidebar items (order: Home, Memos, Dictations, Drafts, then sections)
  # Each row is ~32px, header is ~50px from top
  sidebar:
    region: { x: 0, width: 200 }
    items:
      - home: { x: 100, y: 82 }         # 1st item
      - memos: { x: 100, y: 114 }       # 2nd item (was all-memos)
      - dictations: { x: 100, y: 146 }  # 3rd item
      - drafts: { x: 100, y: 178 }      # 4th item
      # Activity section (has header)
      - actions: { x: 100, y: 238 }     # 5th item (after section header)
      - pending: { x: 100, y: 270 }     # 6th item
      # Tools section (has header)
      - stats: { x: 100, y: 330 }       # 7th item
      - workflows: { x: 100, y: 362 }   # 8th item
      - models: { x: 100, y: 394 }      # 9th item
      - logs: { x: 100, y: 426 }        # 10th item

  content:
    region: { x: 200, width: stretch }
    positions:
      center: { x: 50%, y: 50% }
      top: { x: 50%, y: 100 }

  # Drafts/ScratchPad view targets
  # Targets with .demoAnchor() in SwiftUI are SDK-provided (real coordinates)
  # Others are fallback coordinates used when SDK unavailable
  drafts:
    region: { x: 200, width: stretch }
    items:
      # SDK-provided via DemoKit .demoAnchor() modifiers:
      - text-editor: { x: 400, y: 280 }       # drafts.text-editor (SDK)
      - voice-btn: { x: 65, y: 408 }          # drafts.voice-btn (SDK)
      - accept-btn: { x: 720, y: 408 }        # drafts.accept-btn (SDK)
      - reject-btn: { x: 720, y: 380 }        # drafts.reject-btn (SDK)
      - model-picker: { x: 50, y: 50 }        # drafts.model-picker (SDK)
      # Fallback-only (no SDK anchor yet):
      - dictation-pill: { x: 500, y: 430 }    # Floating dictation button
      - copy-btn: { x: 720, y: 545 }          # Copy to clipboard button
      - model-gpt4o: { x: 50, y: 100 }        # GPT-4o option in dropdown
      - clear-btn: { x: 720, y: 150 }         # Clear text button
